### ISSUE TITLE
Create posts.js to handle all the posts actions (profile, feed, creating, "going", deleting") (controller)

### ISSUE THREAD

**Issue by cunhajulia** [Resilient-Labs/community-catalyst#20]
- [x] git branch _add branch name here_
- [x] git checkout _add branch name here_
- [x] git add .
- [x] git commit -m "_example text: pushing feature [xyz] to [branch name here]_"
- [x]  git push

**Comment by cunhajulia** [comment]
Deadline: by Monday night (I will check in with you on Tuesday Bill!)

**Comment by LDER-DEV** [comment]
sounds good!
