### ISSUE TITLE
Create home.js to render the landing page (controller)

### ISSUE THREAD

**Issue by icodeherenthere** [Resilient-Labs/community-catalyst#27]

**Comment by icodeherenthere** [comment]
- [ ] git branch _add branch name here_
- [ ] git checkout _add branch name here_ 
- [ ] git add .
- [ ] git commit -m "Be Descriptive on what you worked on and please include ticket number"
- [ ] git push

**Comment by icodeherenthere** [comment]
Deadline: by Monday night (I will check in with you on Tuesday Zyonne!)

**Comment by zyonnegb** [comment]
Completed Home.js Controller Ticket #27
