### ISSUE TITLE
Create Post.js (model)

### ISSUE THREAD

**Issue by icodeherenthere** [Resilient-Labs/community-catalyst#28]

**Comment by icodeherenthere** [comment]
- [ ] git branch _add branch name here_
- [ ] git checkout _add branch name here_ 
- [ ] git add .
- [ ] git commit -m "Be descriptive as possible and include the ticket number please"
- [ ] git push

**Comment by icodeherenthere** [comment]
Deadline: by Monday night (I will check in with you on Tuesday Akeem!)

**Comment by AkeemC28** [comment]
I did it!
