### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by juizii** [Resilient-Labs/community-catalyst#32]
Add style and structure

**Comment by Maimounadev** [comment]
got it

**Comment by Jada-Cherie** [comment]
This is going from English to Spanish, correct.

**Comment by juizii** [comment]
- [ ] git branch _add branch name here_
- [ ] git checkout _add branch name here_ 
- [ ] git add .
- [ ] git commit -m "Details and ticket #"
- [ ] git push

**Deadline**:  Monday Night
