### ISSUE TITLE
Sign-up/ Login Page

### ISSUE THREAD

**Issue by juizii** [Resilient-Labs/community-catalyst#46]
Add style and structure

**Comment by bakitucker** [comment]
yes i can when do you need this done by ?

**Comment by bownejp20** [comment]
Thank you Baki! And I think John put the deadline by tonight, but you should double check with himSent from my iPhoneOn Jun 13, 2023, at 4:04 PM, Baki Tucker ***@***.***> wrote:﻿
yes i can when do you need this done by ?
